### ISSUE TITLE
Фідбек ДЗ 2 Тамагочі

### ISSUE THREAD

**Issue by Kashoid23** [Aztec0/RubyHW#3]
Все працює коректно.

- [x] Оновіть ваш приватний методи `spotting` за допомогою операторів `case/when`. У вас є вхідний аргумент num, та досить прості умови які можна реалізувати з `case/when`. В ідеалі всі методи де в умовах `if/else` не фігурує більше однієї змінної (аргумента) в умові, можна обійтись `case/when`
 
https://www.rubyguides.com/2015/10/ruby-case/

Зверніть увагу на переваги attr_reader. Коли ви оголошуєте атрибут з `attr_reader`, це означає, що данний атрибу доступний для зчитування в межах вашого екземпляра. При зчитуванні, не потрібно звертатись до змінної екземпляра, наприклад `@day`, в межах екземпляра можна просто вказувати `day`. Спробуйте.

**Comment by Aztec0** [comment]
Звернув увагу на зауваження і переробив завдання, надіюсь все правильно зрозумів і виконав
