### ISSUE TITLE
Feedback 42 gem

### ISSUE THREAD

**Issue by LVALL** [Aztec0/RubyHW#5]
- [x] згідно умови " Напишіть гем FortyTwo, який би розширював метод Integer і який би додавав до числа метод .forty_two?..."
   Для методів, що повертають булеве значення потрібно додавати до назви знак питання тому у вашому випадку `is_forty_two?`
   
- [x]  табуляція. Відступ має складати 2 пробіли (Можливо гіт не коректно відобразив, тоді не зважайте на цей коментар)
![image](https://user-images.githubusercontent.com/49117430/201516198-c6600192-6177-4411-b20d-95365853af38.png)

**Comment by Aztec0** [comment]
виконано
