### ISSUE TITLE
Feedback HTML creator gem

### ISSUE THREAD

**Issue by LVALL** [Aztec0/RubyHW#6]
- [x] .idea file повинен бути в гітігнорі

- [x] Як щодо того, щоб bypass_html був опціональним атрибутом ? (Згідно умови - false за замовчуванням)

- [x] Булеві значення не має сенсу порівнювати з таким же значенням `bypass_html == false` їх можна напряму використовувати в побудові умови

- [x] рефакторинг

```
    content = Sanitize.fragment(content) unless bypass_html
    content = content unless bypass_html == false
```
Спробуйте замінти повторне присвоєння на тернарний вираз, попередньо проапдейтивши атрибути методу

**Comment by Aztec0** [comment]
виконано
