### ISSUE TITLE
HW5 Feedback

### ISSUE THREAD

**Issue by Boniole** [Aztec0/RubyHW#8]
Anything is good! Great job!

**Comment by Kashoid23** [comment]
- [ ] Маю підозру, що тут повертатиметься помилка https://github.com/Aztec0/RubyHW/blob/main/HW5/fisrt_api/app/controllers/api/v1/articles_controller.rb#L21.
 Ми в ТГ обговорювали, що `loсation: @article` намагається згенерувати шлях якого не визначено з routes.rb, а зважаючи що у вас ще й, навмисна чи ні, помилка в слові `lotation`, ви цього й не помітите. Треба апдейтнути код
 
 - [ ] Оскільки в самому контроллері згенерованому через скаффолд не видно, щоб було значних змін треба обов'язково прочитати https://guides.rubyonrails.org/action_controller_overview.html щоб мати якесь теоретичне розуміння, як це працює.
